name: Docker Build and Push

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: make build

      - name: Test the Docker image
        run: |
          # Run the container without the default entrypoint
          docker run --name test-container -d atas-ssg-builder:latest

          # Check if nginx.conf exists and is valid
          docker exec test-container bash -c "if [ ! -f /etc/nginx/sites-available/site.conf ]; then echo 'nginx.conf does not exist!' && exit 1; else echo 'nginx.conf exists!'; fi"
          docker exec test-container nginx -t

          # Try to start nginx service
          docker exec test-container service nginx start

          # Check if nginx started correctly by checking if the process exists
          docker exec test-container bash -c "if ! pgrep nginx > /dev/null; then echo 'Nginx did not start!' && exit 1; else echo 'Nginx started successfully!'; fi"

          docker stop test-container
          docker rm test-container

      - name: Login to GHCR
        # if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        # if: github.ref == 'refs/heads/main'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set the tag as an environment variable
        # if: github.ref == 'refs/heads/main'
        run: echo "IMAGE_TAG=ghcr.io/atas/ssg-builder:$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        # if: github.ref == 'refs/heads/main'
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          #   username: ${{ github.actor }}
          #   password: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/atas/ssg-builder:latest
            ${{ env.IMAGE_TAG }}
