name: Docker Build and Push

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: make build

      - name: Test the Docker image
        run: |
          # Run the container without the default entrypoint
          docker run --name test-container -d atas-ssg-builder:latest

          # Check if nginx.conf exists and is valid
          docker exec test-container bash -c "if [ ! -f /etc/nginx/sites-available/site.conf ]; then echo 'nginx.conf does not exist!' && exit 1; else echo 'nginx.conf exists!'; fi"
          docker exec test-container nginx -t

          # Try to start nginx service
          docker exec test-container service nginx start

          # Check if nginx started correctly by checking if the process exists
          docker exec test-container bash -c "if ! pgrep nginx > /dev/null; then echo 'Nginx did not start!' && exit 1; else echo 'Nginx started successfully!'; fi"

          docker stop test-container
          docker rm test-container

      - name: Multi platform buid and push to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u atas --password-stdin
          make multi-platform-build
          docker tag ghcr.io/atas/ssg-builder:latest ghcr.io/atas/ssg-builder:$(date +%Y%m%d%H%M)
          docker push ghcr.io/atas/ssg-builder:latest
          docker push ghcr.io/atas/ssg-builder:$(date +%Y%m%d%H%M)
